//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSviewACD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSviewACD.Resource_text", typeof(Resource_text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder itself.
        /// </summary>
        internal static string CurrentFolder_str {
            get {
                return ResourceManager.GetString("CurrentFolder_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Audio.
        /// </summary>
        internal static string FuncCycleAudio_str {
            get {
                return ResourceManager.GetString("FuncCycleAudio_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle the audio channel.
        /// </summary>
        internal static string FuncCycleAudio_tip_str {
            get {
                return ResourceManager.GetString("FuncCycleAudio_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Channel.
        /// </summary>
        internal static string FuncCycleChannel_str {
            get {
                return ResourceManager.GetString("FuncCycleChannel_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle the video and associated audio and subtitle.
        /// </summary>
        internal static string FuncCycleChannel_tip_str {
            get {
                return ResourceManager.GetString("FuncCycleChannel_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Subtitle.
        /// </summary>
        internal static string FuncCycleSubtitle_str {
            get {
                return ResourceManager.GetString("FuncCycleSubtitle_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle the subtitle channel.
        /// </summary>
        internal static string FuncCycleSubtitle_tip_str {
            get {
                return ResourceManager.GetString("FuncCycleSubtitle_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Chapter.
        /// </summary>
        internal static string FuncForwardChapter_str {
            get {
                return ResourceManager.GetString("FuncForwardChapter_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek to next chapter.
        /// </summary>
        internal static string FuncForwardChapter_tip_str {
            get {
                return ResourceManager.GetString("FuncForwardChapter_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FuncPlayExit_str {
            get {
                return ResourceManager.GetString("FuncPlayExit_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to exit the playback window..
        /// </summary>
        internal static string FuncPlayExit_tip_str {
            get {
                return ResourceManager.GetString("FuncPlayExit_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Size.
        /// </summary>
        internal static string FuncResizeOriginal_str {
            get {
                return ResourceManager.GetString("FuncResizeOriginal_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize to original.
        /// </summary>
        internal static string FuncResizeOriginal_tip_str {
            get {
                return ResourceManager.GetString("FuncResizeOriginal_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind Chapter.
        /// </summary>
        internal static string FuncRewindChapter_str {
            get {
                return ResourceManager.GetString("FuncRewindChapter_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek to previous chapter.
        /// </summary>
        internal static string FuncRewindChapter_tip_str {
            get {
                return ResourceManager.GetString("FuncRewindChapter_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind 10sec.
        /// </summary>
        internal static string FuncSeekMinus10sec_str {
            get {
                return ResourceManager.GetString("FuncSeekMinus10sec_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind 10sec.
        /// </summary>
        internal static string FuncSeekMinus10sec_tip_str {
            get {
                return ResourceManager.GetString("FuncSeekMinus10sec_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind 60sec.
        /// </summary>
        internal static string FuncSeekMinus60sec_str {
            get {
                return ResourceManager.GetString("FuncSeekMinus60sec_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind 60sec.
        /// </summary>
        internal static string FuncSeekMinus60sec_tip_str {
            get {
                return ResourceManager.GetString("FuncSeekMinus60sec_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward 10sec.
        /// </summary>
        internal static string FuncSeekPlus10sec_str {
            get {
                return ResourceManager.GetString("FuncSeekPlus10sec_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward 10sec.
        /// </summary>
        internal static string FuncSeekPlus10sec_tip_str {
            get {
                return ResourceManager.GetString("FuncSeekPlus10sec_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward 60sec.
        /// </summary>
        internal static string FuncSeekPlus60sec_str {
            get {
                return ResourceManager.GetString("FuncSeekPlus60sec_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward 60sec.
        /// </summary>
        internal static string FuncSeekPlus60sec_tip_str {
            get {
                return ResourceManager.GetString("FuncSeekPlus60sec_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Normalize.
        /// </summary>
        internal static string FuncSrcAutoVolume_str {
            get {
                return ResourceManager.GetString("FuncSrcAutoVolume_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic normalize audio with FFmpeg dynaudnorm audio filter.
        /// </summary>
        internal static string FuncSrcAutoVolume_tip_str {
            get {
                return ResourceManager.GetString("FuncSrcAutoVolume_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcVolume Down.
        /// </summary>
        internal static string FuncSrcVolumeDown_str {
            get {
                return ResourceManager.GetString("FuncSrcVolumeDown_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down with FFmpeg audio filter.
        /// </summary>
        internal static string FuncSrcVolumeDown_tip_str {
            get {
                return ResourceManager.GetString("FuncSrcVolumeDown_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SrcVolume Up.
        /// </summary>
        internal static string FuncSrcVolumeUp_str {
            get {
                return ResourceManager.GetString("FuncSrcVolumeUp_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up with FFmpeg audio filter.
        /// </summary>
        internal static string FuncSrcVolumeUp_tip_str {
            get {
                return ResourceManager.GetString("FuncSrcVolumeUp_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Display.
        /// </summary>
        internal static string FuncToggleDisplay_str {
            get {
                return ResourceManager.GetString("FuncToggleDisplay_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle elapsed time display.
        /// </summary>
        internal static string FuncToggleDisplay_tip_str {
            get {
                return ResourceManager.GetString("FuncToggleDisplay_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Fullscreen.
        /// </summary>
        internal static string FuncToggleFullscreen_str {
            get {
                return ResourceManager.GetString("FuncToggleFullscreen_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle fullscreen and window.
        /// </summary>
        internal static string FuncToggleFullscreen_tip_str {
            get {
                return ResourceManager.GetString("FuncToggleFullscreen_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string FuncToggleMute_str {
            get {
                return ResourceManager.GetString("FuncToggleMute_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string FuncToggleMute_tip_str {
            get {
                return ResourceManager.GetString("FuncToggleMute_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string FuncTogglePause_str {
            get {
                return ResourceManager.GetString("FuncTogglePause_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Pause.
        /// </summary>
        internal static string FuncTogglePause_tip_str {
            get {
                return ResourceManager.GetString("FuncTogglePause_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        internal static string FuncVolumeDown_str {
            get {
                return ResourceManager.GetString("FuncVolumeDown_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        internal static string FuncVolumeDown_tip_str {
            get {
                return ResourceManager.GetString("FuncVolumeDown_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        internal static string FuncVolumeUp_str {
            get {
                return ResourceManager.GetString("FuncVolumeUp_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        internal static string FuncVolumeUp_tip_str {
            get {
                return ResourceManager.GetString("FuncVolumeUp_tip_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to rename multiple items?.
        /// </summary>
        internal static string RenameMulti_str {
            get {
                return ResourceManager.GetString("RenameMulti_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Upload File(s).
        /// </summary>
        internal static string SelectUploadFiles_str {
            get {
                return ResourceManager.GetString("SelectUploadFiles_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Upload Folder.
        /// </summary>
        internal static string SelectUploadFolder_str {
            get {
                return ResourceManager.GetString("SelectUploadFolder_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to trash items?.
        /// </summary>
        internal static string TrashItems_str {
            get {
                return ResourceManager.GetString("TrashItems_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent folder.
        /// </summary>
        internal static string UpFolder_str {
            get {
                return ResourceManager.GetString("UpFolder_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag item contains some Folder. Do you want to continue to upload?.
        /// </summary>
        internal static string UploadFolder_str {
            get {
                return ResourceManager.GetString("UploadFolder_str", resourceCulture);
            }
        }
    }
}
